# Generated by Django 3.2.5 on 2021-08-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_remove_country_country_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_pic',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='university',
            name='intro_video',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
