# Generated by Django 3.2.5 on 2021-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20210801_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
