# Generated by Django 3.2.5 on 2021-08-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_university_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
